version: '3.5'

services:
  mrsm-compose:
    build:
      context: "./"
      dockerfile: "./docker/Dockerfile"

    ### Override the `bootstrap.sh` entrypoint for interactive development and testing.
    entrypoint: ["/app/docker/sleep_forever.sh"]

    environment:

      MRSM_SQL_APP: |-
        {
          "database": "/meerschaum/sqlite/app.db",
          "flavor": "sqlite"
        }
      MRSM_MQTT_LOCAL: |-
        {
          "host": "localhost"
        }

    network_mode: "host"
    volumes:
      - "./:/app"
    init: true
    tty: true

  mosquitto:
    image: "eclipse-mosquitto"
    network_mode: "host"

