root_dir: "/meerschaum"
project_name: "mqtt-connector"

sync:
  pipes:
    - connector: "mqtt:local"
      metric: "temperature"
      columns:
        datetime: "timestamp"
        id: "device_id"
      parameters:
        fetch:
          topic: "#/temperature"

config:
  meerschaum:
    instance: "sql:main"
    connectors:
      sql:
        main: MRSM{meerschaum:connectors:sql:main}
      mqtt:
        local: MRSM{meerschaum:connectors:mqtt:local}

environment: {}
