root_dir: "/meerschaum"
project_name: "mqtt-connector"

sync:
  schedule: "every 240 seconds"
  pipes:
    - connector: "mqtt:local"
      metric: "foo_bar"
      columns:
        datetime: "timestamp"
        topic: "topic"
      parameters:
        fetch:
          topic:
            - "foo/#"
            - "bar/#"

config:
  meerschaum:
    instance: "sql:main"
    connectors:
      sql:
        main: MRSM{meerschaum:connectors:sql:main}
      mqtt:
        local: MRSM{meerschaum:connectors:mqtt:local}

environment: {}
