root_dir: "/meerschaum"
project_name: "mqtt-connector"

sync:
  schedule: "every 120 seconds"
  args: ["--debug"]
  pipes:
    - connector: "mqtt:local"
      metric: "foo"
      columns:
        datetime: "timestamp"
      parameters:
        fetch:
          topic: "foo/#"

config:
  meerschaum:
    instance: "sql:main"
    connectors:
      sql:
        main: MRSM{meerschaum:connectors:sql:main}
      mqtt:
        local: MRSM{meerschaum:connectors:mqtt:local}

environment: {}
